blog/urls.py
from django.conf.urls import url
from django.urls import path
from .views import HomeView, ArticleDetailView, AddPostView,UpdatePostView,DeletePostView,AddCategoryView,CategoryView,CategoryListView,AddCommentView,DeleteCommentView

app_name = 'blog'

urlpatterns = [
  
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^article/(?P<pk>\d+)$', ArticleDetailView.as_view(), name='article-detail'),
    url(r'^add_post/$', AddPostView.as_view(), name='add-post'),
    url(r'^add_category/$', AddCategoryView.as_view(), name='add-category'),
    url(r'^article/edit/(?P<pk>\d+)$', UpdatePostView.as_view(), name='update-post'),
    url(r'^article/(?P<pk>\d+)/remove$', DeletePostView.as_view(), name='delete-post'),
    #url(r'^category/<str:cats>', CategoryView, name='category'),
    path('category/<str:cats>/', CategoryView, name='category'),
    #path('category-list', CategoryListView, name='category-list'),
    url(r'^category-list/$', CategoryListView, name='category-list'),
    url(r'^article/(?P<pk>\d+)/comment$', AddCommentView.as_view(), name='add-comment'),
    url(r'^comment/(?P<pk>\d+)$', DeleteCommentView.as_view(), name='delete-comment'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from blog import views
from members import views




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('blog.urls', 'blog'), namespace="blog")),
    url(r'^members/', include('django.contrib.auth.urls')),
    url(r'^members/', include('members.urls', 'members')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.conf.urls import url
from django.urls import path
from .views import UserRegisterView,UserEditView,PasswordsChangeView,ShowProfilePageView,EditProfilePageView,CreateProfilePageView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'members'

PasswordsChangeView
urlpatterns = [
    url('^register$', UserRegisterView.as_view(), name='register'),
    url('^login$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url('^edit_profile$', UserEditView.as_view(), name='edit-profile'),
    #url('^password$', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
    #path('password/', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
    #url(r'^password$', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html'), name='change-password'),
    path('password_success', views.password_success, name='password-success'),
    url(r'^(?P<pk>\d+)/profile/$', ShowProfilePageView.as_view(), name='show-profile-page'),
    url(r'^(?P<pk>\d+)/edit_profile_page/$', EditProfilePageView.as_view(), name='edit-profile-page'),
    #path('<int:pk>/profile/', ShowProfilePageView.as_view, name='show-profile-page'),
    url('^create_profile_page$', CreateProfilePageView.as_view(), name='create-profile-page'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self): 
        return reverse('blog:home')

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    
    def __str__(self):
        return str(self.user)

    def get_absolute_url(self): 
        return reverse('blog:home')

class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/")
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images/")
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #body = models.TextField()
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255, default="coding")

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self): 
        return reverse('blog:home')

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = RichTextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s ' % (self.post.title, self.name)

blog/forms.py
from django import forms
from .models import Post
from .models import Category
from .models import Comment


#choices = [('coding','coding'),('sports','sports'),('entertainment','entertainment')]

choices = Category.objects.all().values_list('name','name')

choice_list = []

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','title_tag','author','category','body','header_image','thumbnail')

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter title'}),
            'title_tag': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter title tag'}),
            'author': forms.TextInput(attrs={'class':'form-control','value':' ','id':'user', 'type':'hidden'}),
            #'author': forms.Select(attrs={'class':'form-control'}),
            'category': forms.Select(choices = choice_list,attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class':'form-control','placeholder':'Enter body'}),            
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','title_tag','body','header_image','thumbnail')

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter title'}),
            'title_tag': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter title tag'}),
            #'author': forms.Select(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class':'form-control','placeholder':'Enter body'}),            
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','body')

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter name'}),
            'body': forms.Textarea(attrs={'class':'form-control','placeholder':'Enter body'}),            
        }

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from .models import Post
from .models import Category
from .models import Comment
from .forms import PostForm
from .forms import EditForm
from .forms import CommentForm
from django.urls import reverse_lazy
from django.urls import reverse


class HomeView(ListView):
    paginate_by = 3
    model = Post
    template_name = 'home.html'
    #ordering = ['-id']
    ordering = ['-id']


    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView,self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context

def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'category_list.html',{'cat_menu_list':cat_menu_list})

def CategoryView(request, cats):
    category_post = Post.objects.filter(category=cats)
    return render(request, 'categories.html',{'cats':cats.title(), 'category_post':category_post})



class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_details.html' 

class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    #fields = '__all__'
    #fields = ('title','body')

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'
    #fields = '__all__'
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk'] 
        return super().form_valid(form)
    
    def get_success_url(self):
         #print(self.pk)
         return reverse('blog:article-detail', kwargs={'pk': self.kwargs['pk']})

    #success_url = reverse_lazy('blog:home')

class AddCategoryView(CreateView):
    model = Category
    template_name = 'add_category.html'
    fields = '__all__'
    #fields = ('title','body')

class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'
    #fields = ['title','title_tag','body']

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    #fields = ['title','title_tag','body']
    success_url = reverse_lazy('blog:home')

class DeleteCommentView(DeleteView):
    model = Comment
    template_name = 'delete_comment.html'
    
    
    #fields = ['title','title_tag','body']
    #success_url = reverse_lazy('blog:home')
    
    def get_success_url(self):
        #print(self.pk)
        comment_id = self.kwargs['pk'] 
        comment = Comment.objects.get(pk=comment_id)
        post_id = comment.post.id
        return reverse('blog:article-detail', kwargs={'pk': post_id})

    

blog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Add Category{% endblock %}
{% block content %}
<div class="container">
<br><br>
{% if user.is_authenticated %}

<h1>Add Category</h1>
<div class="form-group">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-secondary">Add Category</button>

</div>
</div>
{% else %}
<p>You're not allowed here</p>
{% endif %}

{% endblock %}

blog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Add comment{% endblock %}
{% block content %}

<div class="container">
<br><br>
<h1>Add Comment</h1>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-secondary">Add comment</button>

</div>
</div>
{% endblock %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}Add post{% endblock %}
{% block content %}
<div class="container">
<br><br>
{% if user.is_authenticated %}

<h1>Add Post</h1>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}

    <button type="submit" class="btn btn-secondary">Post</button>

</div>

<script>
    var name = "{{user.id}}";
    document.getElementById("user").value=name;

</script>

{% else %}
<p>You're not allowed here</p>
{% endif %}

</div>
{% endblock %}

blog/templates/article_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ post.title_tag }}{% endblock %}
{% block content %}
<div class="container">
<br><br>
<h1>{{ post.title }}</h1>

<small>By: {{ post.author.first_name}} {{ post.author.last_name}} - {{ post.post_date}}

    {% if user.is_authenticated %} 
        {% if user.id == post.author.id %}
        <small><a href="{% url 'blog:update-post' post.pk %}" ><button type="button" class="btn btn-success btn-sm">Edit</button></a></small>
                <small><a href="{% url 'blog:delete-post' post.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete</button></a></small>
        {% endif %}
    {% endif %}

    <br>
<hr>
<br>

{% if post.header_image %}
    <center><img src="{{post.header_image.url}}"></center>
{% endif %}
<br>
{{ post.body | safe }}

<br><br>

<div class="card mb-3">
    <div class="row g-0">
    <div class="col-md-2">
        {% if post.author.profile.profile_pic %}
        <img src="{{post.author.profile.profile_pic.url}}" width="150" height="150">
        {% else %}
        <img src="{% static 'blog/images/avatar.png' %}" width="150" height="150">
        {% endif %}
    </div>
    <div class="col-md-8">
        <div class="card-body">
        <h5 class="card-title">{{ post.author.first_name}} {{ post.author.last_name}}</h5>
        <p class="card-text"><small class="small text-muted"><a href="{% url 'members:show-profile-page' post.author.profile.id%}">Profile Page</a> | Author</small></p>
        {% if post.author.profile.bio %}
        <p class="card-text">{{post.author.profile.bio}}</p>
        {% else %}
        <p class="card-text">This is {{ post.author.first_name}}'s bio</p>
        {% endif %}
        </div>
    </div>
    </div>
</div>
<br>


<h3>Comments</h3>
<br>
{% if not post.comments.all %}
    No Comments Yet... 
{% else %}
    {% for comment in post.comments.all %}
        <strong>{{ comment.name }} - {{comment.date_added}}</strong><br>
        {{comment.body | safe }}  
        
        {% if user.id == post.author.id %}
        - <small><a href="{% url 'blog:delete-comment' comment.pk%}" >(Delete)</a></small>
        {% endif %}
        
        <br><br> 

      

    {% endfor %}    

{% endif %}
<br><br>
<a href="{% url 'blog:add-comment' post.pk %}">Add Comment</a>
<hr>
<br><br>
</div>
{% endblock %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <style>
      .dropdown-menu-right {
        right: 0 !important;
    left: auto !important;
}
    </style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Movie Review| {% block title %} {% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'blog:home' %}">Movie Review</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
             
              {% if cat_menu %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  
                  {% for item in cat_menu%}
                  <li><a class="dropdown-item" href="{% url 'blog:category' item %}">{{item}}</a></li>
                  {% endfor %}
                 
                </ul>
              </li>
              
              {% else %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:category-list'%}">Category</a>
              </li>

              {% endif %}

             

              {% if user.is_authenticated %}

            
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:add-post' %}">Add Post</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:add-category' %}">Add Category</a>
              </li>

              
              {% endif %}             
            </ul>

            <ul class="navbar-nav ml-auto">
             
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Hi~! {{user.first_name}} {{user.last_name}}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'members:edit-profile' %}">Account Settings</a>
                    {% if user.profile.id %}
                    <a class="dropdown-item" href="{% url 'members:edit-profile-page' user.profile.id%}">Edit Profile Page</a>
                    <a class="dropdown-item" href="{% url 'members:show-profile-page' user.profile.id%}">Show Profile Page</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'members:create-profile-page' %}">Create Profile Page</a>
                    {% endif %}
                   
                    <a class="dropdown-item" href="{% url 'members:change-password' %}">Change password</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                  </div>
                </li>

                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'members:register' %}">Register</a>
                </li>

                {% endif %}          
             
            </ul>
          



            
          </div>
        </div>
      </nav>

  


    
    
    {% block content%}

    {% endblock %}



  </body>
    

</html>

<!-- Optional JavaScript; choose one of the two! -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js" integrity="sha512-f0VlzJbcEB6KiW8ZVtL+5HWPDyW1+nJEjguZ5IVnSQkvZbwBt2RfCBY0CBO1PsMAqxxrG4Di6TfsCPP3ZRwKpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->

blog/templates/categories.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock %}
{% block content %}
<div class="container">
    <br>
{% if category_post%}

<h1>{{ cats }}</h1>

{% for post in category_post%}

<div class="row">
    <div class="col-md-2"><a href="{% url 'blog:article-detail' post.pk %}"><img class="col-12" src="{{post.thumbnail.url}}"></a></div>
    <div class="col-md-10">

        <h2><a class="text-decoration-none" href="{% url 'blog:article-detail' post.pk %}">{{ post.title }}</a> </h2>
        
        <a class="badge alert-warning" href="{% url 'blog:category' post.category%}">{{post.category}}</a> 
          {{ post.post_date}} 
        
        <br>
        By: {{ post.author.first_name}} {{ post.author.last_name}}
        <p style="text-align: justify;">{{ post.body | slice:":400" | safe  }}</p>
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <small><a href="{% url 'blog:update-post' post.pk %}" ><button type="button" class="btn btn-success btn-sm">Edit</button></a></small>
                <small><a href="{% url 'blog:delete-post' post.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete</button></a></small>
            {% endif %}       
        {% endif %}


    </div>
  </div>

  <br>
{% endfor %}

{% else %}
<h2>Page doesn't exist</h2>
{% endif %}

</div>
{% endblock %}

blog/templates/category_list.html
{% extends 'base.html' %}
{% block title %}Blog Categories{% endblock %}
{% block content %}
<div class="container">
    <br><br>
<h1>Blog Categories</h1>

    {% for item in cat_menu_list%}

    <h4><a class="dropdown-item" href="{% url 'blog:category' item %}">{{item}}</a></h4>

    {% endfor %}
</div>
{% endblock %}

blog/templates/delete_comment.html
{% extends 'base.html' %}
{% block title %}Delete Comment{% endblock %}
{% block content %}
<div class="container">
    <br><br>
{% if user.is_authenticated %}
    
        <h1>Delete Comment</h1>
        <br><br>
        <h5>Delete: {{comment.body | safe}}</h5> 
        <br>
        <form method="POST">
            {% csrf_token %}
            
            <strong>Are you sure?</strong><br><br>
            <button type="submit" class="btn btn-danger">Delete</button>
    

{% else %}
    <p>You're not allowed here</p>
{% endif %}
</div>
{% endblock %}

blog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}Delete post{% endblock %}
{% block content %}
<div class="container">.
    <br><br>
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
        <h1>Delete Post</h1>
        <br><br>
        <h3>Delete: {{post.title}}</h3>
        <br>
        <form method="POST">
            {% csrf_token %}
            
            <strong>Are you sure?</strong><br><br>
            <button type="submit" class="btn btn-danger">Delete</button>
    {% else %}
        <p>You're not allowed here</p>
    {% endif %}

{% else %}
    <p>You're not allowed here</p>
{% endif %}
</div>
{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% load static %}
{% block content %}

<style>


</style>

<div class="">
    <div class="">
      <div style="position: relative;" class="">
         
      <img class="col-12" height="50%" src="{% static 'blog/images/header_imgv1.png' %}">
      </div>
    </div>
</div>
    <hr>
<div class="container">
<h1>Recent Posts</h1>


{% for post in object_list %}

<div class="row">
    <div class="col-md-2"><a href="{% url 'blog:article-detail' post.pk %}"><img class="col-12" src="{{post.thumbnail.url}}"></a></div>
    <div class="col-md-10">

        <h2><a class="text-decoration-none" href="{% url 'blog:article-detail' post.pk %}">{{ post.title }}</a> </h2>
        
        <a class="badge alert-warning" href="{% url 'blog:category' post.category%}">{{post.category}}</a> 
          {{ post.post_date}} 
        
        <br>
        By: {{ post.author.first_name}} {{ post.author.last_name}}
        <p style="text-align: justify;">{{ post.body | slice:":400" | safe  }}</p>
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <small><a href="{% url 'blog:update-post' post.pk %}" ><button type="button" class="btn btn-success btn-sm">Edit</button></a></small>
                <small><a href="{% url 'blog:delete-post' post.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete</button></a></small>
            {% endif %}       
        {% endif %}


    </div>
  </div>

  <br>

   



    
{% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1" >&laquo; first</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      <li class="page-item"><span class="current page-link">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span></li>
   

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" >Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" >last &raquo;</a></li>
      {% endif %}
    </ul>
  </nav>

</div>

    <!-- Footer -->
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">
          <!-- Section: Social media -->
      
      
      
          <!-- Section: Text -->
          <section class="mb-4">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget sit amet tellus cras adipiscing enim eu turpis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Blandit cursus risus at ultrices mi. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Lectus vestibulum mattis ullamcorper velit sed. Fermentum dui faucibus in ornare. Sed viverra tellus in hac habitasse platea. Rhoncus urna neque viverra justo.
            </p>
          </section>
          <!-- Section: Text -->
      
      
          <!-- Section: Links -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2021 All Rights Reserve
         
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
{% endblock %}

blog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}Update post{% endblock %}
{% block content %}
<div class="container">
    <br><br>
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
        <h1>Update Post</h1>

        <form method="POST">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}

            <button type="submit" class="btn btn-secondary">Update</button>
    {% else %}
        <p>You're not allowed here</p>
    {% endif %}


{% else %}
<p>You're not allowed here</p>
{% endif %}
</div>
{% endblock %}